platform :ios, '9.3'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/tbzgarnett/TBZTargetActionDemoSpec.git'

target 'AfterZujianhuaDemo' do
  pod 'ZujianhuaDemoInfoCategoryKit', '~>0.1.1'
  pod 'ZujianhuaDemoValidateCategoryKit', '~>0.1.1'
  pod 'ZujianhuaDemoValidateKit', '~>0.1.1'
  pod 'ZujianhuaDemoInfoKit', '~>0.1.1'
end
