platform :ios, '9.3'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/tbzgarnett/TBZTargetActionDemoSpec.git'

target 'AfterZujianhuaDemo' do
  pod 'ZujianhuaDemoInfoCategoryKit'
  pod 'ZujianhuaDemoValidateCategoryKit'
  pod 'ZujianhuaDemoValidateKit'
  pod 'ZujianhuaDemoInfoKit'
end
